# Kubernetes CronJob for Automated Database Backups

apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: production
spec:
  # Run daily at 2:00 AM UTC
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              # Install AWS CLI
              apk add --no-cache aws-cli curl
              
              # Run backup script
              /scripts/postgres-backup.sh
              
              # Verify backup
              if [ $? -eq 0 ]; then
                echo "Backup completed successfully"
                exit 0
              else
                echo "Backup failed"
                exit 1
              fi
            env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DATABASE_NAME
              value: "technician_marketplace"
            - name: S3_BUCKET
              value: "technician-marketplace-backups"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: slack-webhook-url
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            - name: backup-storage
              mountPath: /var/backups/postgres
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: production
spec:
  # Run daily at 3:00 AM UTC
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mongodb-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: mongo:6
            command:
            - /bin/sh
            - -c
            - |
              # Install AWS CLI
              apt-get update && apt-get install -y awscli
              
              # Create backup
              TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
              BACKUP_FILE="mongodb_${TIMESTAMP}.archive"
              
              mongodump --uri="$MONGODB_URI" \
                        --archive="/backup/${BACKUP_FILE}" \
                        --gzip
              
              # Upload to S3
              aws s3 cp "/backup/${BACKUP_FILE}" \
                        "s3://${S3_BUCKET}/mongodb/${BACKUP_FILE}"
              
              # Clean up old backups
              find /backup -name "mongodb_*.archive" -type f -mtime +30 -delete
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: uri
            - name: S3_BUCKET
              value: "technician-marketplace-backups"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: production
data:
  postgres-backup.sh: |
    #!/bin/bash
    # Backup script content from postgres-backup.sh
    # (Content would be embedded here)
